services:
  folium-minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: folium-minio
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web Console
    env_file:
      - path: .env
        required: false
    environment:
      - MINIO_PROMETHEUS_AUTH_TYPE=public
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  minio_data:
